[project]
name = "reindeerrush-bd"
version = "0.1.0"
description = "Reindeer Rush mini-game extra package for Ballsdex v3."
authors = [{name = "haymooed"}]
requires-python = ">=3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["reindeerrush_app"]
