[project]
name = "preview-bd"
version = "1.0.0"
description = "Preview card images in Ballsdex v3 without owning them."
authors = [
    {name = "ariel-aram"},
    {name = "haymooed"}
]
requires-python = ">=3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["preview_app"]
